### PR TITLE
Fix: fix functionality to add and remove all tags from assets (fixes #241 & #142)

### LINKED ISSUE #241: Not able to remove last tag
### What happened?

Able to add and remove tags as expected but when trying to remove the last tag and saving it does not remove it. 

### Expected behaviour

_No response_

### Steps to reproduce

Add tags to an asset and save, edit it and try to remove all the assets. 

### Authoring tool version

Latest

### Framework version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Add a link to the original issue)
Fixes https://github.com/adapt-security/adapt-authoring-ui/issues/241 
Fixes https://github.com/adapt-security/adapt-authoring-ui/issues/142

[//]: # (Delete as appropriate)
### Fix
* fix functionality to add and remove all tags from assets (fixes #241 & #142)

### CODE REVIEW

File: app/modules/assetManagement/views/assetManagementEditAssetView.js [hunk 1]
```diff
@@ -64,12 +63,24 @@ define([
       if(Object.keys(data).length) return data;
     },
```
Comment (chris-steele) [inline app/modules/assetManagement/views/assetManagementEditAssetView.js:65]: Some nice use of Backbone/Underscore functions in `getAttributesToSave` 👍
