### PR TITLE
Fix: name and tag filters now work together (fixes #291)

### LINKED ISSUE #291: Search by tag not restored after search by name
### What happened?

I filtered courses using search by tag. I then filtered courses using search by name, which overrides search by tag (it is not a compound filter). The tag parameter I chose remains, however.

When I cleared the search by name parameter, the results were not filtered by tag, despite the tag parameter remaining.

### Expected behaviour

When I search by name any selected tags should be removed (or vice versa).

OR

The filter should be compound: i.e. if there are tags selected and a parameter given to search by name then the matching courses should satisfy both queries.

### PR DESCRIPTION
**Pull request by chris-steele**
#291 

### Fix
* name and tag filters now work together

### CODE REVIEW

File: app/modules/projects/views/projectsView.js [hunk 1]
```diff
@@ -50,10 +58,11 @@ define(function(require){
 
     initUserPreferences: function() {
       var prefs = this.getUserPreferences();
-
+      this.filterText = prefs.search;
+      this.filterTags = prefs.tags;
```
Comment (taylortom) [inline app/modules/projects/views/projectsView.js:62]: Don't think we should restore previous filters as it might cause confusion if items are seemingly missing. Restoring views/sorts is ok as it doesn't restrict what's shown.

Happy to be challenged on this though.

**Review by taylortom — CHANGES_REQUESTED** [review]
As per discussion, the following changes are needed:
- Filters should be compound
- Make sure filters are stored in `sessionStorage` (i.e. temporary storage), not `localStorage`

**Comment by taylortom** [comment]
Is this ready for review/merge now?
