### PR TITLE
Fix: prevent Origin.editor.data.content from being overwritten until fetch completed (fixes #274)

### LINKED ISSUE #274: Intermitent issue of components not showing in the sidebar
### What happened?

Clicked 'add component', sidebar appears but is blank, close and reopen and all components are then shown. This is a very intermitent issue which has no console errors shown and I'm unable to replicate on a regular basis.

### Expected behaviour

All components should be shown ever time. 

### Steps to reproduce

I'm unable to replicate on a regular basis, but click 'add component' and occasionally the sidebar appears empty.

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Add a link to the original issue)
#274 

[//]: # (Delete as appropriate)
### Fix
* prevent Origin.editor.data.content from being overwritten until fetch completed (fixes #274)

### CODE REVIEW

File: app/modules/editor/global/editorDataLoader.js [hunk 1]
```diff
@@ -20,19 +20,20 @@ define(function(require) {
...
+            Origin.editor.data.contentTemp.fetch(),
+            Origin.editor.data.componentTypesTemp.fetch()
           ]);
         } catch(e) {
           return handleError();
         }
+        Origin.editor.data.content = Origin.editor.data.contentTemp
+        Origin.editor.data.componentTypes = Origin.editor.data.componentTypesTemp
         Origin.editor.data.course = Origin.editor.data.content.findWhere({ _type: 'course' });
         Origin.editor.data.config = Origin.editor.data.content.findWhere({ _type: 'config' });
```
Comment (taylortom) [inline app/modules/editor/global/editorDataLoader.js:39]: Can we just tweak this so that these are local vars, rather than something that's globally accessible on Origin? We could probably also do with shifting things around a bit to help with readability:
```js 
try {
  await Promise.all([
    async () => {
      const content = new ContentCollection(undefined, { _courseId: Origin.location.route1 });
      await content.fetch();
      Origin.editor.data.content = content;
      Origin.editor.data.course = content.findWhere({ _type: 'course' });
      Origin.editor.data.config = content.findWhere({ _type: 'config' });
    },
    async () => {
      const componentTypes = new ContentPluginCollection(undefined, { type: 'component' });
      await componentTypes.fetch();
      Origin.editor.data.componentTypes = componentTypes;
    }
  ]);
} catch(e) {
  return handleError();
}
```
**:warning: Caveat**: haven't tested this...

Comment (joe-allen-89) [reply app/modules/editor/global/editorDataLoader.js:39]: Agree, local vars would be the better option. This is currently throwing some errors but will take a look at those shortly.
