### PR TITLE
Fix: update editorPageView render to try/catch consistent with editorDataLoader (fixes #271)

### LINKED ISSUE #271: Copy and Paste not working as expected.
### What happened?

Currently the copy and paste function seems to not be working as expected. 

When copying a component to an empty block, clone fires as expected, but on page reload no component is visible. 
When copying an article/block/page with content the article/block/page is duplicated as expected but non of the children are. No console/network errors.

When throttling you are also able to press copy/paste multiple times before the first request is completed, this leads to an error saying "unable to fetch course data", this then crashed the testing site for me with numerous errors, screenshots below.

@taylortom - just an fyi tag.  

image

image

### Steps to reproduce

Create a course and attempt to copy and paste both with and without throttling. 

### Authoring tool version

rc.4

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Add a link to the original issue)
#271 

[//]: # (Delete as appropriate)
### Fix
* Update editorPageView render to try/catch consistent with editorDataLoader (#271)

[//]: # (Mention any other dependencies)

### CODE REVIEW

File: app/modules/editor/contentObject/views/editorPageView.js [hunk 1]
```diff
@@ -47,15 +47,18 @@ define(function(require){
...
-          this.addArticleViews();
-          return returnVal;
-        },
-        error: () => Origin.Notify.alert({ type: 'error', text: Origin.l10n.t('app.errorfetchingdata') })
-      });
+    render: async function() {
+      try {
+        await Promise.all([
+          Origin.editor.data.content.fetch(),
+        ]);
```
Comment (taylortom) [inline app/modules/editor/contentObject/views/editorPageView.js:54]: We don't need the `Promise.all` here, as we're just doing one fetch:

```suggestion
        await Origin.editor.data.content.fetch();
```

Otherwise, looks good :)

**Review by taylortom — CHANGES_REQUESTED** [review]

**Review by chris-steele — APPROVED** [review]

**Review by taylortom — APPROVED** [review]
